### PR TITLE
Special purpose distros

### PR DESCRIPTION
**Pull request by dhamaniasad**
This pull request is in regards to #13. Feedback is welcome and appreciated.

### CODE REVIEW

**Comment by nickedes** [comment]
:+1:

**Comment by aleksandar-todorovic** [comment]
Good job, but maybe we should drop the `screenshot` and `default desktop environment` from the special purpose section? I mean, people are looking at them because they're created for a specific purpose. I don't think that people actually care about the DE and a screenshot in this case. They just care about what's their purpose.

**Comment by dhamaniasad** [comment]
@aleksandar-todorovic That makes sense. I've updated the pull request.

**Comment by aleksandar-todorovic** [comment]
Great! If there are no more recommendations in the next couple of hours, I'll merge this. :)

**Pull request merged**
